[qwen_config]
logging_dir = "./logs"
flash_attn = true
sdpa = false
split_attn = true
guidance_scale = 1
network_args = true
network_module = "networks.lora_qwen_image"
lr_scheduler = "cosine_with_min_lr"
lr_scheduler_num_cycles = 1
lr_decay_steps = 0.2
lr_scheduler_min_lr_ratio = 0.1
cuda_allow_tf32 = true
cuda_cudnn_benchmark = true
mixed_precision = "bf16"
fp8_base = true
fp8_scaled = true
persistent_data_loader_workers = true
use_pinned_memory_for_block_swap = true
compile = true
compile_backend = "inductor"
compile_mode = "max-autotune-no-cudagraphs"
compile_dynamic = "auto"
compile_cache_size_limit = 32
img_in_txt_in_offloading = true
optimizer_type = "adamw"
gradient_checkpointing = true
gradient_checkpointing_cpu_offload = false

[wan_config]
logging_dir = "./logs"
vae_cache_cpu = true
force_v2_1_time_embedding = true
preserve_distribution_shape = true
flash_attn = true
split_attn = true
guidance_scale = 1
gradient_checkpointing = true
gradient_accumulation_steps = 1
network_module = "networks.lora_wan"
lr_scheduler = "cosine_with_min_lr"
lr_scheduler_num_cycles = 1
lr_decay_steps = 0.2
lr_scheduler_min_lr_ratio = 0.1
cuda_allow_tf32 = true
cuda_cudnn_benchmark = true
mixed_precision = "fp16"
fp8_base = true
fp8_scaled = true
persistent_data_loader_workers = true
use_pinned_memory_for_block_swap = true
img_in_txt_in_offloading = true
optimizer_type = "pytorch_optimizer.Fira"
wandb_api_key = ""
log_with = ""

# 缓存设置
[qwen_cache]
batch_size = 16
vae_tiling = false
vae_chunk_size = 0
vae_spatial_tile_sample_min_size = 256
fp8_vl = false

[wan_cache]
vae_cache_cp = true
batch_size = 16

[[task]]
task = "i2v-A14B"
output_name = "video1"
output_dir = "./output/video1"
max_train_epochs = 1
save_every_n_epochs = 2
network_dim = 32
network_alpha = 16
learning_rate = 0.0001
timestep_sampling = "shift"
blocks_to_swap = 16
loraplus_lr_ratio = 4
min_timestep = 0
max_timestep = 900
discrete_flow_shift = 5
max_data_loader_n_workers = 8
dit = "D:/models/diffusion_models/wan/wan2.2_i2v_low_noise_14B_fp16.safetensors"
vae = "D:/models/vae/wan_2.1_vae.safetensors"
t5 = "D:/models/text_encoders/umt5-xxl-enc-bf16.pth"
clip = "F:/Downloads/open-clip-xlm-roberta-large-vit-huge-14.safetensors"
i2v = true
dataset_config = "./src/video1.toml"
log_tracker_name = "video1"
rank = 32
weight_decay = 0.01
update_proj_gap = 50
scale = 1
projection_type = "std"
train_type = "Wan2.2"
