[general]
resolution = [512, 512]
caption_extension = ".txt"
batch_size = 1
enable_bucket = true
bucket_no_upscale = false
num_repeats = 1

[[datasets]]
video_directory = "./dataset/video"
cache_directory = "./dataset/video/cache"
target_frames = [1, 13, 25]
frame_sample = 4
frame_extraction = "uniform"
max_frames = 81
